services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: approval-db

  mqtt:
    image: emqx/emqx:latest
    environment:
      - "EMQX_LISTENERS_TCP_DEFAULT_BIND=1884"
      - "EMQX_NAME=MQTT"
      - "EMQX_HOST=localhost"
    ports:
      - "1883:1883"
      - "1884:1884"
      - "18083:18083"
